import { useState, useEffect } from 'react';
import api from '../utils/api';
import toast from 'react-hot-toast';
import { Download, FileText, Printer, X } from 'lucide-react';

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  
  const [reportType, setReportType] = useState('monthly');
  const [generating, setGenerating] = useState(false);

  const [viewingReport, setViewingReport] = useState<any>(null);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const res = await api.get('/reports');
      setReports(res.data);
    } catch (err) {
      toast.error('Failed to fetch reports');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const now = new Date();
      await api.post('/reports/generate', { 
        type: reportType,
        year: now.getFullYear(),
        month: now.getMonth() + 1,
        quarter: Math.ceil((now.getMonth() + 1) / 3),
        semester: now.getMonth() < 6 ? 1 : 2
      });
      toast.success('Report generated successfully');
      fetchReports();
    } catch (err) {
      toast.error('Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  const handleDownloadExcel = async (id: number) => {
    try {
      const res = await api.get(`/reports/${id}/excel`, { responseType: 'blob' });
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `Report_${id}.xlsx`);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (err) {
      toast.error('Failed to download Excel');
    }
  };

  const handleViewReport = async (id: number) => {
    try {
      const res = await api.get(`/reports/${id}`);
      setViewingReport(res.data);
    } catch (err) {
      toast.error('Failed to fetch report details');
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) return <div className="p-8">Loading...</div>;

  return (
    <div className="p-8">
      <div className="mb-8 print:hidden">
        <h1 className="text-2xl font-bold text-[#1A2340]">Inventory Reports</h1>
        <p className="text-sm text-gray-500 mt-1">Generate and view inventory quantity reports</p>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 mb-8 flex items-end gap-4 print:hidden">
        <div className="flex-1 max-w-xs">
          <label className="block text-sm font-medium text-gray-700 mb-2">Report Type</label>
          <select 
            className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            value={reportType}
            onChange={e => setReportType(e.target.value)}
          >
            <option value="monthly">Monthly</option>
            <option value="quarterly">Quarterly</option>
            <option value="semestral">Semestral</option>
            <option value="yearly">Yearly</option>
          </select>
        </div>
        <button 
          onClick={handleGenerate}
          disabled={generating}
          className="bg-blue-600 text-white px-6 py-2 rounded-lg font-medium hover:bg-blue-700 transition-colors disabled:opacity-50"
        >
          {generating ? 'Generating...' : 'Generate Report'}
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden print:hidden">
        <div className="p-4 border-b border-gray-200 bg-gray-50">
          <h3 className="font-bold text-gray-700">Reports Archive</h3>
        </div>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b border-gray-200">
              <th className="p-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Report ID</th>
              <th className="p-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Type</th>
              <th className="p-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Period</th>
              <th className="p-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Generated On</th>
              <th className="p-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Generated By</th>
              <th className="p-4 text-xs font-bold text-gray-500 uppercase tracking-wider text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {reports.length === 0 ? (
              <tr><td colSpan={6} className="p-8 text-center text-gray-500">No reports generated yet.</td></tr>
            ) : reports.map(report => (
              <tr key={report.id} className="hover:bg-gray-50 transition-colors">
                <td className="p-4 font-mono text-sm text-gray-600">REP-{String(report.id).padStart(4, '0')}</td>
                <td className="p-4 text-sm font-medium text-gray-900 capitalize">{report.report_type}</td>
                <td className="p-4 text-sm text-gray-600">{report.period_label}</td>
                <td className="p-4 text-sm text-gray-600">{new Date(report.createdAt).toLocaleString()}</td>
                <td className="p-4">
                  {report.is_auto ? (
                    <span className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-purple-100 text-purple-700">Auto-Generated</span>
                  ) : (
                    <span className="text-sm text-gray-600">Admin</span>
                  )}
                </td>
                <td className="p-4 text-right flex justify-end gap-2">
                  <button onClick={() => handleViewReport(report.id)} className="p-1.5 text-gray-500 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors" title="View / Print">
                    <FileText size={18} />
                  </button>
                  <button onClick={() => handleDownloadExcel(report.id)} className="p-1.5 text-gray-500 hover:text-green-600 hover:bg-green-50 rounded transition-colors" title="Download Excel">
                    <Download size={18} />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {viewingReport && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 print:bg-white print:static print:inset-auto print:flex-col print:z-auto">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-5xl max-h-[90vh] flex flex-col print:shadow-none print:max-h-none print:w-full">
            <div className="px-6 py-4 border-b border-gray-100 flex justify-between items-center print:hidden">
              <h2 className="text-lg font-bold text-gray-800">Report Preview: {viewingReport.period_label}</h2>
              <div className="flex gap-2">
                <button onClick={handlePrint} className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors">
                  <Printer size={16} /> Print
                </button>
                <button onClick={() => setViewingReport(null)} className="text-gray-400 hover:text-gray-600 p-2">
                  <X size={20} />
                </button>
              </div>
            </div>
            
            <div className="p-8 overflow-y-auto print:overflow-visible print:p-0">
              <div className="text-center mb-8">
                <h1 className="text-2xl font-bold uppercase">Inventory Quantity Report</h1>
                <h2 className="text-lg font-semibold mt-1">{viewingReport.period_label}</h2>
                <p className="text-sm text-gray-600 mt-2">Department: {viewingReport.department || 'All Departments'}</p>
                <p className="text-sm text-gray-600">Generated: {new Date(viewingReport.createdAt).toLocaleString()}</p>
              </div>

              <table className="w-full text-left border-collapse border border-gray-300 text-sm">
                <thead>
                  <tr className="bg-gray-100">
                    <th className="border border-gray-300 p-2 font-bold">Stock No.</th>
                    <th className="border border-gray-300 p-2 font-bold">Description</th>
                    <th className="border border-gray-300 p-2 font-bold">Category</th>
                    <th className="border border-gray-300 p-2 font-bold">Unit</th>
                    <th className="border border-gray-300 p-2 font-bold text-right">Opening Qty</th>
                    <th className="border border-gray-300 p-2 font-bold text-right">Issued Qty</th>
                    <th className="border border-gray-300 p-2 font-bold text-right">Remaining Qty</th>
                  </tr>
                </thead>
                <tbody>
                  {viewingReport.data.map((item: any, idx: number) => (
                    <tr key={idx}>
                      <td className="border border-gray-300 p-2 font-mono text-xs">{item.stock_no}</td>
                      <td className="border border-gray-300 p-2">{item.description}</td>
                      <td className="border border-gray-300 p-2">{item.category}</td>
                      <td className="border border-gray-300 p-2">{item.unit}</td>
                      <td className="border border-gray-300 p-2 text-right">{item.opening_qty}</td>
                      <td className="border border-gray-300 p-2 text-right">{item.issued_qty}</td>
                      <td className="border border-gray-300 p-2 text-right font-medium">{item.remaining_qty}</td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr className="bg-gray-50 font-bold">
                    <td colSpan={4} className="border border-gray-300 p-2 text-right">TOTALS:</td>
                    <td className="border border-gray-300 p-2 text-right">{viewingReport.data.reduce((a: number, b: any) => a + b.opening_qty, 0)}</td>
                    <td className="border border-gray-300 p-2 text-right">{viewingReport.data.reduce((a: number, b: any) => a + b.issued_qty, 0)}</td>
                    <td className="border border-gray-300 p-2 text-right">{viewingReport.data.reduce((a: number, b: any) => a + b.remaining_qty, 0)}</td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
